"""empty message

Revision ID: 0e021dc3e8c0
Revises: e452a0dc8061
Create Date: 2024-02-28 13:31:06.670361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e021dc3e8c0'
down_revision = 'e452a0dc8061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('rate', sa.String(length=16), nullable=False))
    op.add_column('news', sa.Column('authority', sa.String(length=64), nullable=True))
    op.add_column('news', sa.Column('source_url', sa.String(length=128), nullable=False))
    op.add_column('news', sa.Column('date', sa.String(length=32), nullable=False))
    op.add_column('news', sa.Column('forward_num', sa.String(length=16), nullable=False))
    op.add_column('news', sa.Column('comment_num', sa.String(length=16), nullable=False))
    op.add_column('news', sa.Column('like_num', sa.String(length=16), nullable=False))
    op.add_column('news', sa.Column('detail_url', sa.String(length=128), nullable=False))
    op.alter_column('news', 'source',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=64),
               nullable=False)
    op.drop_column('news', 'comment4')
    op.drop_column('news', 'comment2')
    op.drop_column('news', 'comment10')
    op.drop_column('news', 'comments_count')
    op.drop_column('news', 'comment8')
    op.drop_column('news', 'picture')
    op.drop_column('news', 'comment3')
    op.drop_column('news', 'category')
    op.drop_column('news', 'office')
    op.drop_column('news', 'comment9')
    op.drop_column('news', 'participants')
    op.drop_column('news', 'comment6')
    op.drop_column('news', 'comment7')
    op.drop_column('news', 'link')
    op.drop_column('news', 'location')
    op.drop_column('news', 'comment5')
    op.drop_column('news', 'time')
    op.drop_column('news', 'keywords')
    op.drop_column('news', 'comment1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('comment1', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('keywords', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('news', sa.Column('time', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment5', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('location', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('news', sa.Column('link', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment7', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment6', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('participants', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('comment9', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('office', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('news', sa.Column('category', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment3', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('picture', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('news', sa.Column('comment8', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comments_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('comment10', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment2', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('news', sa.Column('comment4', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column('news', 'source',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('news', 'detail_url')
    op.drop_column('news', 'like_num')
    op.drop_column('news', 'comment_num')
    op.drop_column('news', 'forward_num')
    op.drop_column('news', 'date')
    op.drop_column('news', 'source_url')
    op.drop_column('news', 'authority')
    op.drop_column('news', 'rate')
    # ### end Alembic commands ###
