"""empty message

Revision ID: 10cac2b52fe1
Revises: 37fcc580c264
Create Date: 2024-04-17 22:33:49.444825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cac2b52fe1'
down_revision = '37fcc580c264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('eamil', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'eamil')
    # ### end Alembic commands ###
