"""empty message

Revision ID: 30085d2b33b4
Revises: 53007baa0ae5
Create Date: 2023-12-07 23:58:57.333228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30085d2b33b4'
down_revision = '53007baa0ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_ibfk_1', 'news', type_='foreignkey')
    op.drop_column('news', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('news_ibfk_1', 'news', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
