"""empty message

Revision ID: 34f66a3beddc
Revises: 3c8bc81139b3
Create Date: 2024-03-29 21:47:34.794256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34f66a3beddc'
down_revision = '3c8bc81139b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follow_link', sa.String(length=1024), nullable=False),
    sa.Column('follow_content', mysql.TEXT(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=16), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('forward_num', sa.Integer(), nullable=False),
    sa.Column('comment_num', sa.Integer(), nullable=False),
    sa.Column('like_num', sa.Integer(), nullable=False),
    sa.Column('detail_url', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
