"""empty message

Revision ID: 3c8bc81139b3
Revises: 46341664c922
Create Date: 2024-03-23 09:58:52.974670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8bc81139b3'
down_revision = '46341664c922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=16), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('forward_num', sa.Integer(), nullable=False),
    sa.Column('comment_num', sa.Integer(), nullable=False),
    sa.Column('like_num', sa.Integer(), nullable=False),
    sa.Column('detail_url', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=16), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('forward_num', sa.Integer(), nullable=False),
    sa.Column('comment_num', sa.Integer(), nullable=False),
    sa.Column('like_num', sa.Integer(), nullable=False),
    sa.Column('detail_url', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rumors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=16), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('forward_num', sa.Integer(), nullable=False),
    sa.Column('comment_num', sa.Integer(), nullable=False),
    sa.Column('like_num', sa.Integer(), nullable=False),
    sa.Column('detail_url', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rumors')
    op.drop_table('refute')
    op.drop_table('news')
    # ### end Alembic commands ###
