"""empty message

Revision ID: 42725861b987
Revises: 10cac2b52fe1
Create Date: 2024-04-17 22:36:45.584649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42725861b987'
down_revision = '10cac2b52fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=False))
    op.drop_column('user', 'eamil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('eamil', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
