"""empty message

Revision ID: 47b0d7f7d37c
Revises: 9cb39dca5841
Create Date: 2024-04-11 15:16:27.393009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47b0d7f7d37c'
down_revision = '9cb39dca5841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'date',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('news', 'date',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('refute', 'date',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('rumors', 'date',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rumors', 'date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('refute', 'date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('news', 'date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('follows', 'date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
