"""empty message

Revision ID: 53007baa0ae5
Revises: b091c470611c
Create Date: 2023-12-07 23:45:58.453869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53007baa0ae5'
down_revision = 'b091c470611c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'time',
               existing_type=sa.String(length=128),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
