"""empty message

Revision ID: 9cb39dca5841
Revises: 34f66a3beddc
Create Date: 2024-04-11 15:06:44.094063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cb39dca5841'
down_revision = '34f66a3beddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'rate',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('news', 'rate',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('refute', 'rate',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('rumors', 'rate',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rumors', 'rate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('refute', 'rate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('news', 'rate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('follows', 'rate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
