"""empty message

Revision ID: ded63c6dc18b
Revises: 0e021dc3e8c0
Create Date: 2024-02-28 14:16:57.296576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ded63c6dc18b'
down_revision = '0e021dc3e8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'forward_num',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('news', 'comment_num',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('news', 'like_num',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'like_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('news', 'comment_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('news', 'forward_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
